---
title: "Final Project"
output: html_document
date: "2025-02-26"

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Load the libraries
```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(shiny)
library(janitor)
library(naniar)
library(ggmap)
```

```{r}
options(scipen = 999)
```


## Load the Data
```{r}
cardiac <- read_csv("data/cardiac-surgery.csv") %>% clean_names()
```

```{r}
glimpse(cardiac)
```

## Cleaning the Data
```{r}
cardiac <- cardiac %>% 
  mutate(year_of_hospital_discharge = as.factor(year_of_hospital_discharge)) %>% 
  mutate(facility_id = as.factor(facility_id))
```

```{r}
cardiac <- cardiac %>% 
  mutate(across(everything(), tolower))
cardiac
```

```{r}
cardiac <- cardiac %>% 
  #mutate(across(everything) ~ str_replace(" ", "_"))
  #mutate(across(everything) ~ sr_remove("-"))
  mutate(hospital_name = str_replace(hospital_name, " ", "_")) %>% 
  mutate(detailed_region = str_replace(detailed_region, " ", "_")) %>% 
  mutate(comparison_results = str_replace(comparison_results, " ", "_")) %>% 
  mutate(hospital_name = str_remove(hospital_name, "-")) %>% 
  mutate(detailed_region = str_remove(detailed_region, "-"))
cardiac
```


## Plots

What is the procedure with the highest observed mortality rate?
```{r}
cardiac %>% 
  group_by(procedure) %>% 
  summarize(avg_mortality = mean(observed_mortality_rate)) %>% 
  ggplot(aes(x = reorder(procedure, avg_mortality), y = avg_mortality))+
  geom_col(color = "black", fill = "lightblue")+
  coord_flip()+
  labs(title = "Average Observed Mortality Rate by Procedure",
       x = "Procedure",
       y = "Mortality Rate")+
  theme_light(base_size = 12)
```



## Shiny App
```{r}

```

