---
title: "Og Shiny"
output: html_document
date: "2025-03-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(shinydashboard)

ui <- dashboardPage(skin = "purple",
                    
  dashboardHeader(title = "Cardiac Dashboard"),
  
  ## Sidebar content
  dashboardSidebar(
    sidebarMenu(
      
      menuItem("Mortality Rate", 
               tabName = "dashboard", 
               icon = icon("skull")),
      
      menuItem("Procedures", 
               tabName = "widgets", 
               icon = icon("stethoscope")),
      menuItem("Cases",
               tabName = "cases",
               icon = icon("folder-open")),
      menuItem("Maps",
               tabName = "map",
               icon = icon("earth-americas")),
      menuItem("NYC Maps",
               tabName = "nyc",
               icon = icon("hotel"))
    )
    ),
  
  ## Body content
  dashboardBody(
    
    tabItems(
  
      ## First tab content    
      tabItem(tabName = "dashboard", 
              h1(strong("These are plots produced based on the mortality rate observed in each New York hospital based on cardiac surgery results."), style = "font-size:20px"),
        fluidRow(
          box(plotOutput("plot1a", height = 250), status = "primary", solidHeader = T, width = 6, title = "Plot"), 
          box(title = "Controls", status = "info", solidHeader = T, width = 6, 
              selectInput("region", 
                          "Select Region:", 
                          choices=unique(cardiac$region))
          )
          ),
        fluidRow(
          box(plotOutput("plot1b", height = 250), status = "primary", solidHeader = T, width = 6, title = "Plot"),
          box(title = "Controls", status = "info", solidHeader = T, width = 6,
              selectInput("year",
                          "Select Year:",
                          choices = unique(cardiac$year_of_hospital_discharge)))
          ),
        fluidRow(
          box(plotOutput("plot1c", height = 250), status = "primary", solidHeader = T, width = 6, title = "Plot"),
          box(title = "Controls", status = "info", solidHeader = T, width = 6,
              selectInput("hospital",
                          "Select Hospital:",
                          choices = unique(cardiac$hospital_name)))
          )
          ),

      ## Second tab item 
      tabItem(tabName = "widgets",
              h1(strong("These are the plots observing the procedures performed in New York Hospitals"), style = "font-size:20px"),
        fluidRow(
          box(plotOutput("plot2a", height = 250), status = "primary", solidHeader = T, width = 6, title = "Plot"), # box is a container for the plot
          box(title = "Controls", status = "info", solidHeader = T, width = 6, # box is a container for the controls
              radioButtons("x", 
               "Select X Axis:", 
               choices=c("year_of_hospital_discharge", "region"),
               selected="year_of_hospital_discharge")
          )
          ),
        fluidRow(
          box(plotOutput("plot2b", height = 250), status = "primary", solidHeader = T, width = 6, title = "Plot"),
          box(title = "Controls", status = "info", solidHeader = T, width = 6,
              selectInput("p",
                          "Select Year:",
                          choices = unique(cardiac$year_of_hospital_discharge)))
          ),
        fluidRow(
          box(plotOutput("plot2c", height = 250), status = "primary", solidHeader = T, width = 6, title = "Plot"),
          box(title = "Controls", status = "info", solidHeader = T, width = 6,
              selectInput("h",
                          "Select Hospital:",
                          choices = unique(cardiac$hospital_name)))
          )
          ),
      
      ## Third tab item
      tabItem(tabName = "cases",
              h1(strong("These are plots produced based on the number of cases of cardiac surgery performed in New York Hospitals."), style = "font-size:20px"),
        fluidRow(
          box(plotOutput("plot3a", height = 250), status = "primary", solidHeader = T, width = 6, title = "Plot"), # box is a container for the plot
          box(title = "Controls", status = "info", solidHeader = T, width = 6, # box is a container for the controls
              selectInput("a", 
               "Select Hospital:", 
               choices=c(unique(cardiac$hospital_name))
          )
          )
          ),
        fluidRow(
          box(plotOutput("plot3b", height = 250), status = "primary", solidHeader = T, width = 6, title = "Plot"), # box is a container for the plot
          box(title = "Controls", status = "info", solidHeader = T, width = 6, # box is a container for the controls
              selectInput("b", 
               "Select Year:", 
               choices=c(unique(cardiac$year_of_hospital_discharge))
          )
          )
          )
          ),
        
        tabItem(tabName = "map",
                h1(strong("These are overall maps addressing different scenarios based on our dataset."), style = "font-size:20px"),
          fluidRow(
            box(plotOutput("plot4a", height = 450), status = "primary", solidHeader = T, width = 6, title = "Map"),
            box(plotOutput("plot4b", height = 450), status = "primary", solidHeader = T, width = 6, title = "Map"),
            box(plotOutput("plot4c", height = 450), status = "primary", solidHeader = T, width = 6, title = "Map"),
            box(plotOutput("plot4d", height = 450), status = "primary", solidHeader = T, width = 6, title = "Map")
          )
          ),
      tabItem(tabName = "nyc",
              h1(strong("These are maps zoomed in on New York City addressing different scenarios based on our dataset."), style = "font-size:20px"),
              fluidRow(
            box(plotOutput("plot5a", height = 450), status = "primary", solidHeader = T, width = 6, title = "Map"),
            box(plotOutput("plot5b", height = 450), status = "primary", solidHeader = T, width = 6, title = "Map"),
            box(plotOutput("plot5c", height = 450), status = "primary", solidHeader = T, width = 6, title = "Map")
          )
          )
          )
          )
  )
          
server <- function(input, output, session) {
  
  session$onSessionEnded(stopApp)

  output$plot1a <- renderPlot({

    cardiac %>%
      filter(region == input$region) %>%
      ggplot(aes(x = observed_mortality_rate))+ 
      geom_density(color = "black", fill = "steelblue", alpha = 0.6)+
      labs(title = "Observed Mortality Rate Distribution by Region",
           x = "Mortality Rate",
           y = "Proportion of Hospitals in the Region")
  })
  
  output$plot1b <- renderPlot({

    cardiac %>%
      filter(year_of_hospital_discharge == input$year) %>%
      ggplot(aes(x = observed_mortality_rate))+ 
      geom_density(color = "black", fill = "steelblue", alpha = 0.6)+
      labs(title = "Observed Mortality Rate Distribution by Year",
           x = "Mortality Rate",
           y = "Proportion of Hospitals")
  })
  
  output$plot1c <- renderPlot({

    cardiac %>% 
      filter(hospital_name == input$hospital) %>% 
      group_by(year_of_hospital_discharge, hospital_name) %>% 
      summarize(avg_mortality = mean(observed_mortality_rate), .groups = 'keep') %>% 
      ggplot(aes(x = as.factor(year_of_hospital_discharge), y = avg_mortality, group = hospital_name))+
      geom_line()+
      geom_point(na.rm = T)+
      labs(title = "Mortality Rate Over Time",
           x = "Year",
           y = "Mortality Rate")
  })
  
  
    output$plot2a <- renderPlot({ #this is a bigger picture of the two plots shown below
    
    cardiac %>%
      ggplot(aes_string(x= input$x, fill = "procedure"))+
      geom_bar(position="dodge", alpha=0.8, color="black")+
      coord_flip()+
      labs(x= NULL, y=NULL, fill= "Procedure")
    
  })
    
    output$plot2b <- renderPlot({
    
    cardiac %>% 
      filter(year_of_hospital_discharge == input$p) %>% 
      group_by(procedure) %>% 
      summarize(avg_mortality = mean(observed_mortality_rate)) %>% 
      ggplot(aes(x = reorder(procedure, avg_mortality), y = avg_mortality))+
      geom_col(color = "black", fill = "lightblue")+
      coord_flip()+
      labs(title = "Average Observed Mortality Rate by Procedure",
          x = "Procedure",
          y = "Mortality Rate")+
      theme_light(base_size = 14)
      
    })
    
     output$plot2c <- renderPlot({
    
    cardiac %>% 
      filter(hospital_name == input$h) %>% 
      group_by(procedure, hospital_name) %>% 
      summarize(procedure_cases = sum(number_of_cases), .groups = 'keep') %>% 
      ggplot(aes(x = procedure, y = procedure_cases))+
      geom_col(color = "black", fill = "lightblue")+
      labs(title = "Number of Cases per Procedure",
          x = "Procedure",
          y = "Number of Cases")+
      theme_light(base_size = 14)
      
    })
    
    output$plot3a <- renderPlot({
    
    cardiac %>% 
      filter(hospital_name == input$a) %>% 
      group_by(year_of_hospital_discharge) %>% 
      summarize(total_cases_a = sum(number_of_cases)) %>% 
      ggplot(aes_string(x="year_of_hospital_discharge", y = "total_cases_a"))+
      geom_col(alpha=0.8, color="black", fill = "steelblue")+
      labs(title = "Number of Cases per Year",
           x= "Year", 
           y= "Number of Cases")+
        theme_light(base_size = 14)
    
  })
    
    
  output$plot3b <- renderPlot({
    
    cardiac %>% 
      filter(year_of_hospital_discharge == input$b) %>% 
      group_by(facility_id, procedure) %>% 
      summarize(total_procedures = sum(number_of_cases), avg_mortality = mean(observed_mortality_rate)) %>%
      ggplot(aes(x = total_procedures, y = avg_mortality))+
      geom_point(color = "olivedrab", na.rm = T) +
      labs(title = "Average Mortality Rate compared with Procedure Numbers ",
       x = "Total Number of Procedures",
       y = "Mortality Rate")+
     theme(axis.text.y = element_text(angle = 0, hjust = 1, size = 5))+
     theme_classic()+
     scale_x_log10()+
     geom_smooth(method=lm, se=F, formula = 'y ~ x')
    
  })
  
  output$plot4a <- renderPlot({
    
      ggmap(maptotal) + 
  geom_point(data = x, aes(facility_longitude, facility_latitude, size = 1.5), na.rm= T) + labs(x= "Longitude", y= "Latitude", title="Cardiac Locations")
    
  })
  
  output$plot4b <- renderPlot({
    
    ggmap(maptotal) + 
  geom_point(data = x, aes(facility_longitude, facility_latitude, colour  = number_of_cases, size = 1.5), na.rm= T) + #WE just add the chart in without using ggplot! 
  labs(x= "Longitude", y= "Latitude", title="Cardiac Locations") 
    
  })
  
  output$plot4c <- renderPlot({
    
    ggmap(maptotal) + 
  geom_point(data = x, aes(facility_longitude, facility_latitude, colour  = average_moratality_rate, size = 1.5), na.rm= T) + #WE just add the chart in without using ggplot! 
  labs(x= "Longitude", y= "Latitude", title="Cardiac Locations") 
    
  })
  
  output$plot4d <- renderPlot({
    
    ggmap(maptotal) + 
  geom_point(data = x, aes(facility_longitude, facility_latitude, colour  = total_deaths, size = 1.5), na.rm= T) + #WE just add the chart in without using ggplot! 
  labs(x= "Longitude", y= "Latitude", title="Cardiac Locations") 
    
  })
  
  output$plot5a <- renderPlot({
    
    ggmap(mapnyc) + 
  geom_point(data = x, aes(facility_longitude, facility_latitude, colour  = average_moratality_rate,size = 2.5), na.rm= T) + 
  labs(x= "Longitude", y= "Latitude", title="Cardiac Locations")
    
  })
  
  output$plot5b <- renderPlot({
    
    ggmap(mapnyc) + 
  geom_point(data = x, aes(facility_longitude, facility_latitude, colour  = number_of_cases, size = 2.5), na.rm= T) + 
  labs(x= "Longitude", y= "Latitude", title="Cardiac Locations")
    
  })
  
  output$plot5c <- renderPlot({
    
    ggmap(mapnyc) + 
  geom_point(data = x, aes(facility_longitude, facility_latitude, colour  = total_deaths, size = 2.5), na.rm= T) + 
  labs(x= "Longitude", y= "Latitude", title="Cardiac Locations")
    
  })
}

shinyApp(ui, server)
```
```

